# Generated by Django 4.1.3 on 2022-11-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_company_address_company_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=32, null=True),
        ),
    ]
