# Generated by Django 4.1.3 on 2022-12-15 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_item_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='delivery',
            new_name='nutrient',
        ),
    ]
