# Generated by Django 4.1.3 on 2022-12-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_delivery_item_nutrient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
