# Generated by Django 4.1.3 on 2022-12-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_item_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='author',
        ),
    ]
